### ISSUE TITLE
Add links to experiences

### ISSUE THREAD

**Issue by this-oliver** [this-oliver/this-oliver#195]
Problem: experiences don't link to artefacts that show some sort of example of the project

**Comment by HavreLoic** [comment]
Hi @this-oliver is this issue still open?

**Comment by this-oliver** [comment]
Hi @HavreLoic ! Sorry for the later reply! I managed to resolve it this weekend. If you are still interested in open source contributing, feel free to check our my other repos that could do with some help:

- [fist-bump](https://github.com/this-oliver/fist-bump) - a tool for keeping package.jsons up to date
- [build-a-theme](https://github.com/this-oliver/build-a-theme) - a tool that lets you build themes and preview the results in real-time
